server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # SPA fallback — все неизвестные пути отдаём index.html
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Кэш статики
  location ~* \.(?:js|css|svg|woff2?|ttf|eot|ico|png|jpg|jpeg|gif|webp)$ {
    expires 30d;
    access_log off;
    add_header Cache-Control "public, max-age=2592000";
  }
}
